### PR TITLE
Add comments

### PR DESCRIPTION
**Pull request by kevgo**
@charlierudolph @allewun

### CODE REVIEW

**Comment by charlierudolph** [comment]
On the next release I'm hoping we can just update the source to:
```ruby
def install
  bin.install Dir['src']
  man1.install Dir["man/man1/*.1"]
end
```
With that I don't comments are really necessary

**Comment by kevgo** [comment]
That sounds like a good plan to me. If you plan on doing that very soon, I'm fine with throwing away this PR. Otherwise we could simply merge it now, and then you clean it up later when you simplify the installation.

**Comment by kevgo** [comment]
@charlierudolph can this be deleted?

**Comment by charlierudolph** [comment]
Yep

**Pull request closed without merging**
